version: '3.8'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
