version: '3.8'
services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/usr/src/app
      - ./instance/esbay.db:/usr/src/app/esbay.db